# Generated by Django 6.0.2 on 2026-02-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_mensajecontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
