# Generated by Django 6.0.2 on 2026-02-19 15:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_mensajecontacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
